# Generated by Django 4.1.1 on 2022-09-05 15:46

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('type', models.CharField(choices=[('sole', 'Sole Proprietorship'), ('sme', 'Small and Medium-Sized Enterprise'), ('corp', 'Corporation'), ('cso', 'Civil Society Organization')], max_length=5)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('url', models.URLField(blank=True)),
                ('employee_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
